### ISSUE TITLE
document webpacker setup

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1890]
Currently, the previous way of running webpacker in development is broken, and the new way isn't yet documented. This is the error message:

```
bess@paz:~/projects/laevigata$ ./bin/webpack-dev-server                                                                                                                                                                                
/home/bess/.rvm/gems/ruby-2.4.2@laevigata/gems/webpacker-3.6.0/lib/webpacker/dev_server_runner.rb:55:in `exec': No such file or directory - /home/bess/projects/laevigata/node_modules/.bin/webpack-dev-server (Errno::ENOENT)         
        from /home/bess/.rvm/gems/ruby-2.4.2@laevigata/gems/webpacker-3.6.0/lib/webpacker/dev_server_runner.rb:55:in `block in execute_cmd'                                                                                            
        from /home/bess/.rvm/gems/ruby-2.4.2@laevigata/gems/webpacker-3.6.0/lib/webpacker/dev_server_runner.rb:54:in `chdir'                                                                                                           
        from /home/bess/.rvm/gems/ruby-2.4.2@laevigata/gems/webpacker-3.6.0/lib/webpacker/dev_server_runner.rb:54:in `execute_cmd'                                                                                                     
        from /home/bess/.rvm/gems/ruby-2.4.2@laevigata/gems/webpacker-3.6.0/lib/webpacker/dev_server_runner.rb:12:in `run'                                                                                                             
        from /home/bess/.rvm/gems/ruby-2.4.2@laevigata/gems/webpacker-3.6.0/lib/webpacker/runner.rb:6:in `run'                                                                                                                         
        from ./bin/webpack-dev-server:14:in `<main>' 
```

**Comment by RachelDCE** [comment]
README updated.
