### ISSUE TITLE
Fix flaky GraduationJob test

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#2183]
**ISSUE**
We're seeing the following failure intermittently:
```
Failure/Error:
  next if Hyrax::PermissionTemplateAccess
            .find_by(permission_template_id: admin_set.permission_template.id,
                     agent_id:   'registered',
                     access:     'deposit',
                     agent_type: 'group')

ActiveRecord::RecordNotFound:
  Couldn't find Hyrax::PermissionTemplate
./lib/workflow_setup.rb:156:in `block in everyone_can_deposit_everywhere'
./lib/workflow_setup.rb:154:in `everyone_can_deposit_everywhere'
./lib/workflow_setup.rb:44:in `setup'
./spec/jobs/graduation_job_with_embargo_spec.rb:46:in `block (3 levels) in <top (required)>'
```
e.g. https://app.circleci.com/pipelines/github/curationexperts/laevigata/504/workflows/bd115b16-c926-461a-b739-cb9c864d3763/jobs/536/tests#failed-test-0

This appears not to be occurring in the tests themselves, but in the setup block here
https://github.com/curationexperts/laevigata/blob/main/spec/jobs/graduation_job_with_embargo_spec.rb#L45-L47

When the `Hyrax::PermissionTemplate` class can't be found (isn't loaded), it causes all tests in the context to fail.

**Comment by mark-dce** [comment]
This appears to be occurring based on the randomized order of previous tests that may or may not be flagged `clean: true`.  It appear that running `ActiveFedora::Cleaner.clean!` once before the workflow setup ensures consistent state for the workflows to be setup and subsequent tests to be run.

**Comment by mark-dce** [comment]
Fixed in #2185
