### ISSUE TITLE
cap deploy resque-pool restart fails with running workers

### ISSUE THREAD

**Issue by acozine** [curationexperts/laevigata#226]
As a developer, I would like to be able to deploy fresh code without disturbing the ongoing activity of the background jobs. Cap deploy should allow resque to finish currently active jobs, then pick up new jobs from a fresh pool of workers working off the new code.

EXPECTED BEHAVIOR:
Cap deploy allows active resque workers to finish their jobs and starts a new pool of workers on the freshly deployed code.

ACTUAL BEHAVIOR:
Cap deploy succeeds, but no new resque-pool is started. Error message in cap deploy:
```
00:54 resque:pool:stop
      01 export master_pid=$(cat /opt/laevigata/shared/tmp/pids/resque-pool.pid) && kill -QUIT $master_pid
    ✔ 01 deploy@emory-stress-test.curationexperts.com 0.120s
00:55 passenger:restart
      01 mkdir -p /opt/laevigata/releases/20170523152240/tmp
    ✔ 01 deploy@emory-stress-test.curationexperts.com 0.103s
      02 touch /opt/laevigata/releases/20170523152240/tmp/restart.txt
    ✔ 02 deploy@emory-stress-test.curationexperts.com 0.170s
01:05 resque:pool:start
      01 cd /opt/laevigata/releases/20170523152240 && bundle exec resque-pool -d -E production -c config/resque-pool.yml -p /opt/laevigata/shared/tmp/pids/resque-pool.pid
      01 bundler: failed to load command: resque-pool (/opt/laevigata/shared/bundle/ruby/2.3.0/bin/resque-pool)
      01 RuntimeError: Pidfile already exists at /opt/laevigata/shared/tmp/pids/resque-pool.pid and process is still running.
      01   /opt/laevigata/shared/bundle/ruby/2.3.0/gems/resque-pool-0.6.0/lib/resque/pool/cli.rb:74:in `manage_pidfile'
      01   /opt/laevigata/shared/bundle/ruby/2.3.0/gems/resque-pool-0.6.0/lib/resque/pool/cli.rb:16:in `run'
      01   /opt/laevigata/shared/bundle/ruby/2.3.0/gems/resque-pool-0.6.0/bin/resque-pool:7:in `<top (required)>'
      01   /opt/laevigata/shared/bundle/ruby/2.3.0/bin/resque-pool:22:in `load'
      01   /opt/laevigata/shared/bundle/ruby/2.3.0/bin/resque-pool:22:in `<top (required)>'
      01
    ✔ 01 deploy@emory-stress-test.curationexperts.com 1.050s
```
Active workers do finish their jobs, but resque-pool does not restart.

**Comment by acozine** [comment]
Looks like configuring restarts to use `--hot-swap` may do what we want - see https://github.com/nevans/resque-pool#zero-downtime-code-deploys

**Comment by acozine** [comment]
Using resque-pool from github enables hot-swap, which does exactly what we want. That work is on the `hot-swap-workers` branch. I also need to update the resque-pool service script to start pools with `hot-swap`, so a pool gets started automatically on reboot.

**Comment by acozine** [comment]
Just tested with the pre-existing resque-pool service script, and it seems to work fine. The script starts up an old-style pool with a PIDfile. If it has an active worker when fresh code is deployed, capistrano kills the master PID, starts a hot-swap pool, and everything works. So I think we're good to go. I'm going to investigate moving to sidekiq, since the last commit to resque-pool is from May of 2016, but meanwhile the system is functioning well.
