### ISSUE TITLE
Statistics link on Admin Dashboard is broken

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#764]
**STEPS TO REPRODUCE**
1. Log in as an administrator (e.g. tezproxy)
2. Click on the 'Administration' link in the top banner
3. Click on 'Statistics' in the left navigation menu

**EXPECTED RESULT**
Some statistics page displays correctly

**ACTUAL RESULT**
"Something went wrong" - see partial log in comments

**NOTES**
Occurring on all environments:
Prod/Staging/QA: Version v1.0.2 updated 14 September 2017.

**ACCEPTANCE**
- ~Determine if there is a corresponding issue in samvera/hyrax and link to it~
OR
- [x] Fix the issue causing this
OR
- ~Disable the "Statistics" link and add hover text that the issue will be resolved at a future point~

**Comment by mark-dce** [comment]
Partial output from production.log
```
I, [2017-10-06T13:02:56.389089 #1691]  INFO -- : [0d8c2545-99b2-44b6-b9df-f70fc448210a] Started GET "/admin/stats?locale=en" for 174.141.199.210 at 2017-10-06 13:02:56 -0400
I, [2017-10-06T13:02:56.390249 #1691]  INFO -- : [0d8c2545-99b2-44b6-b9df-f70fc448210a] Processing by Hyrax::Admin::StatsController#show as HTML
I, [2017-10-06T13:02:56.390300 #1691]  INFO -- : [0d8c2545-99b2-44b6-b9df-f70fc448210a]   Parameters: {"locale"=>"en"}
I, [2017-10-06T13:02:56.396932 #1691]  INFO -- : [0d8c2545-99b2-44b6-b9df-f70fc448210a]   Rendering /opt/laevigata/shared/bundle/ruby/2.3.0/gems/hyrax-1.0.3/app/views/hyrax/admin/stats/show.html.erb within layouts/admin
I, [2017-10-06T13:02:56.397876 #1691]  INFO -- : [0d8c2545-99b2-44b6-b9df-f70fc448210a]   Rendered /opt/laevigata/shared/bundle/ruby/2.3.0/gems/hyrax-1.0.3/app/views/hyrax/admin/stats/_date_form.html.erb (0.6ms)
I, [2017-10-06T13:02:56.406551 #1691]  INFO -- : [0d8c2545-99b2-44b6-b9df-f70fc448210a]   Rendered /opt/laevigata/shared/bundle/ruby/2.3.0/gems/hyrax-1.0.3/app/views/hyrax/admin/stats/_works.html.erb (8.5ms)
I, [2017-10-06T13:02:56.410073 #1691]  INFO -- : [0d8c2545-99b2-44b6-b9df-f70fc448210a]   Rendered /opt/laevigata/shared/bundle/ruby/2.3.0/gems/hyrax-1.0.3/app/views/hyrax/admin/stats/_new_users.html.erb (3.3ms)
I, [2017-10-06T13:02:56.422572 #1691]  INFO -- : [0d8c2545-99b2-44b6-b9df-f70fc448210a]   Rendered /opt/laevigata/shared/bundle/ruby/2.3.0/gems/hyrax-1.0.3/app/views/hyrax/admin/stats/_deposits.html.erb (12.3ms)
I, [2017-10-06T13:02:56.422673 #1691]  INFO -- : [0d8c2545-99b2-44b6-b9df-f70fc448210a]   Rendered /opt/laevigata/shared/bundle/ruby/2.3.0/gems/hyrax-1.0.3/app/views/hyrax/admin/stats/_stats_by_date.html.erb (25.5ms)
I, [2017-10-06T13:02:56.422788 #1691]  INFO -- : [0d8c2545-99b2-44b6-b9df-f70fc448210a]   Rendered /opt/laevigata/shared/bundle/ruby/2.3.0/gems/hyrax-1.0.3/app/views/hyrax/admin/stats/show.html.erb within layouts/admin (25.7ms)
I, [2017-10-06T13:02:56.422990 #1691]  INFO -- : [0d8c2545-99b2-44b6-b9df-f70fc448210a] Completed 500 Internal Server Error in 33ms (ActiveRecord: 3.3ms)
F, [2017-10-06T13:02:56.424813 #1691] FATAL -- : [0d8c2545-99b2-44b6-b9df-f70fc448210a]   
F, [2017-10-06T13:02:56.424855 #1691] FATAL -- : [0d8c2545-99b2-44b6-b9df-f70fc448210a] ActionView::Template::Error (Unable to find user 'P0335035'
Results was: #<Enumerator: ["P6235048", 7, "P1529006", 3, "P0335035", 2, "P4925162", 2, "8w32r560x", 1, "c247ds08x", 1, "cn69m413j", 1, "k930bx00t", 1, "mtkowal", 1, "qv33rw64w", 1]:each_slice(2)>):
F, [2017-10-06T13:02:56.424967 #1691] FATAL -- : [0d8c2545-99b2-44b6-b9df-f70fc448210a]     1: <h3>Deposits By Users (<%= @presenter.date_filter_string %>)</h3>
[0d8c2545-99b2-44b6-b9df-f70fc448210a]     2: <ul>
[0d8c2545-99b2-44b6-b9df-f70fc448210a]     3:   <% @presenter.depositors.each do |usr| %>
[0d8c2545-99b2-44b6-b9df-f70fc448210a]     4:     <li>
[0d8c2545-99b2-44b6-b9df-f70fc448210a]     5:       <a href="<%= hyrax.profile_path(usr[:key]) %>" title="View user's profile"><%= usr[:user].name %></a>
[0d8c2545-99b2-44b6-b9df-f70fc448210a]     6:       deposited <%= pluralize(usr[:deposits], "file") %>
F, [2017-10-06T13:02:56.424993 #1691] FATAL -- : [0d8c2545-99b2-44b6-b9df-f70fc448210a]   
F, [2017-10-06T13:02:56.425040 #1691] FATAL -- : [0d8c2545-99b2-44b6-b9df-f70fc448210a] hyrax (1.0.3) app/services/hyrax/statistics/depositors/summary.rb:21:in `block in depositors'
[0d8c2545-99b2-44b6-b9df-f70fc448210a] hyrax (1.0.3) app/services/hyrax/statistics/depositors/summary.rb:19:in `each'
```

**Comment by bess** [comment]
This error is being caused when a user who has a deposit has been deleted, or their ppid has changed. We have a lot of this on the QA server, for example. I made the feature more robust, so instead of failing in those cases, it prints "Unknown User ID ID_NUMBER"
